<?php
/**
 * @file
 * Hide file from multi-value field if it exists in in other field in display.
 */

/**
 * Implements hook_field_formatter_settings_form().
 */
function insert_hide_file_field_formatter_settings_form_alter(&$settings_form, $context) {
  if (in_array($context['field']['type'], array('image', 'file'))) {
    $options = array();

    $instances = field_info_instances($context['instance']['entity_type'], $context['instance']['bundle']);
    foreach ($instances as $field_name => $instance) {
      $options[$field_name] = $instance['label'];
    }
    $settings_form['insert_hide_file'] = array(
      '#type' => 'select',
      '#title' => t('Hide item if exists in:'),
      '#multiple' => TRUE,
      '#default_value' => $context['instance']['display'][$context['view_mode']]['settings']['insert_hide_file'],
      '#options' => $options,
    );
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function insert_hide_file_field_formatter_info_alter(&$info) {
  // Added to all formatters.
  foreach ($info as $formatter_key => &$formatter) {
    if (in_array('image', $formatter['field types']) || in_array('file', $formatter['field types'])) {
      $formatter['settings']['insert_hide_file'] = array();
    }
  }
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function insert_hide_file_field_formatter_settings_summary_alter(&$summary, array $context) {
  switch ($context['field']['type']) {
    case 'file':
    case 'image':
      if (!empty($summary)) {
        $summary .= '<br />';
      }
      if (!empty($context['instance']['display'][$context['view_mode']]['settings']['insert_hide_file'])) {
        $summary .= t('insert_hide_file filter enabled for @field', array('@field' => implode(', ', $context['instance']['display'][$context['view_mode']]['settings']['insert_hide_file'])));
      }
      else {
        $summary .= t('insert_hide_file filter is disabled');
      }
      break;

    default:
      break;
  }
}

/**
 * Implements hook_field_attach_view_alter().
 */
function insert_hide_file_field_attach_view_alter(&$output, $context) {
  foreach (element_children($output) as $field_name) {

    $entity_type = $output[$field_name]['#entity_type'];
    $bundle = $output[$field_name]['#bundle'];
    $view_mode = $output[$field_name]['#view_mode'];
    $entity = $output[$field_name]['#object'];

    $formatter_settings = field_formatter_settings_get_instance_display_settings($entity_type, $field_name, $bundle, $view_mode);
    if (isset($formatter_settings['insert_hide_file']) && !empty($formatter_settings['insert_hide_file'])) {
      $i = 0;
      foreach ($output[$field_name]['#items'] as $delta => $item) {
        // If file exist in preselected field...
        if (_insert_hide_file_parse_row($item, $entity, $formatter_settings['insert_hide_file'])) {
          // ...hide it.
          hide($output[$field_name][$delta]);
          $i++;
        }
      }
      // Hide field if nothing to show.
      if ($i == sizeof($output[$field_name]['#items'])) {
        hide($output[$field_name]);
      }
    }
  }
}

/**
 * Parse single value.
 *
 * @param $file
 * @param $entity
 * @param $fields
 *
 * @return bool
 */
function _insert_hide_file_parse_row($file, $entity, $fields) {
  $scheme = file_uri_scheme($file['uri']);
  $path = substr($file['uri'], strlen($scheme) + 3);

  foreach ($fields as $field_name) {
    if (isset($entity->{$field_name}) && is_array($entity->{$field_name})) {

      $data = array(
        'needle' => $path,
        'score' => FALSE,
      );

      array_walk_recursive($entity->{$field_name}, function ($value, $key) use (&$data) {
        if (!$data['score']) {
          if (strpos($value, $data['needle'])) {
            $data['score'] = TRUE;
          }
        }
      });

      if ($data['score']) {
        return TRUE;
      }
    }
  }

  return FALSE;
}
